In [ ]:
from sklearn.datasets import load_digits

In [ ]:
digits=load_digits()
print(digits.data.shape)

(1797, 64)


In [ ]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [ ]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [ ]:
from sklearn import tree
from sklearn import model_selection
import numpy as np

In [ ]:
kf=model_selection.KFold(n_splits=10)
kf.get_n_splits(digits.data,digits.target)
print(kf)
for  train_index,test_index in kf.split(digits.data):
  X_first_train, X_first_test = digits.data[train_index], digits.data[test_index]
  y_first_train, y_first_test = digits.target[train_index], digits.target[test_index]
  print("TRAIN:", X_first_train, "TEST:", X_first_test)

KFold(n_splits=10, random_state=None, shuffle=False)
TRAIN: [[ 0.  0.  7. ... 12.  3.  0.]
 [ 0.  1. 12. ...  9.  4.  0.]
 [ 0.  0.  5. ...  0.  0.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]] TEST: [[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  0. ... 12.  0.  0.]
 [ 0.  0.  6. ... 10.  1.  0.]
 [ 0.  0.  0. ...  8.  0.  0.]]
TRAIN: [[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]] TEST: [[ 0.  0.  7. ... 12.  3.  0.]
 [ 0.  1. 12. ...  9.  4.  0.]
 [ 0.  0.  5. ...  0.  0.  0.]
 ...
 [ 0.  0.  3. ...  8.  0.  0.]
 [ 0.  0.  5. ...  1.  0.  0.]
 [ 0.  0.  6. ... 11.  1.  0.]]
TRAIN: [[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ...

In [ ]:
first_classifier = tree.DecisionTreeClassifier()

first_classifier.fit(X_first_train,y_first_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
model_selection.cross_val_score(first_classifier,X_first_test,y_first_test,cv=10)

array([0.72222222, 0.5       , 0.44444444, 0.88888889, 0.77777778,
       0.88888889, 0.72222222, 0.83333333, 0.66666667, 0.82352941])

In [ ]:
onetask_classifier = tree.DecisionTreeClassifier()

#onetask_classifier.fit()

model_selection.cross_val_score(onetask_classifier,digits.data,digits.target,cv=10).mean()

0.823026070763501

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn import ensemble

In [ ]:
second_classifier = BaggingClassifier(n_estimators=100)

#onetask_classifier.fit()

model_selection.cross_val_score(second_classifier,digits.data,digits.target,cv=10).mean()

0.9242768466790814

In [ ]:
digits.data.shape[0]
import math

In [ ]:
features_quantity=math.sqrt(digits.data.shape[0])
features_quantity/digits.data.shape[0]
digits.data.shape[0]

1797

In [ ]:
third_classifier = BaggingClassifier(n_estimators=100,max_features=int(features_quantity))
#third_classifier = BaggingClassifier(n_estimators=100,n_features_=features_quantity)

#onetask_classifier.fit()

model_selection.cross_val_score(third_classifier,digits.data,digits.target,cv=10).mean()
#third_classifier.

0.9420980757293606

In [ ]:
tree_classifier = tree.DecisionTreeClassifier(max_features=int(features_quantity))
fourth_classifier = BaggingClassifier(tree_classifier, n_estimators=100,max_features=int(features_quantity))
#onetask_classifier.fit()

model_selection.cross_val_score(fourth_classifier,digits.data,digits.target,cv=10).mean()

0.9460024829298572